Add spaces_permissions and users_permissions to grant_token
pubnub/ruby pull request #131
Opened 2022-07-14 10:57 UTC by kleewho

2022-07-22 15:26 UTC, parfeon requested changes
@kleewho there is very small changes required

2022-07-22 15:26 UTC, parfeon commented on lib/pubnub/validators/grant_token.rb
> +          not(@users_permissions.empty?)
Why not like this:
```suggestion
        entities_set = !@spaces_permissions.empty? ||
          !@users_permissions.empty?
```

2022-07-22 15:26 UTC, parfeon commented on lib/pubnub/validators/grant_token.rb
> +          not(@uuids.empty?)
Why not like this:
```suggestion
        objects_set = !@channels.empty? ||
          !@channel_groups.empty? ||
          !@uuids.empty?
```

2022-07-22 15:26 UTC, parfeon commented on spec/examples/grant_token_examples_spec.rb
> +      uuid: "ruby-test-uuid-client-one",
@kleewho this will conflict after recent merge of `user_id` changes.

2022-07-26 11:48 UTC, parfeon approved these changes
LGTM!

2022-07-26 14:00 UTC, kleewho commented
@client-engineering-bot release as v5.1.0

2022-07-26 14:34 UTC, merged